# Streamlit secrets configuration for deployment
# Copy this file to .streamlit/secrets.toml and add your actual API key

[general]
OPENAI_API_KEY = "your-openai-api-key-here"

# Optional: Add your organization ID if you have one
# OPENAI_ORGANIZATION = "your-org-id-here" 